DROP TABLE SAIDAS_ESTOQUE;
DROP TABLE ITEM_ESTOQUE;
DROP TABLE ENTRADAS_ESTOQUE;
DROP TABLE LOCALIZACOES;
DROP TABLE FORNECEDORES;
DROP TABLE ITENS;

CREATE TABLE ITENS (
    CODIGO_ITEM INT NOT NULL,
    NOME_ITEM VARCHAR(50) NOT NULL,
    TIPO_ITEM VARCHAR(50) NOT NULL,
    DESCRICAO_ITEM VARCHAR(50),
    VOLUME NUMBER(9,2) NOT NULL,
    CONSTRAINT ITENS_PK PRIMARY KEY (CODIGO_ITEM)
);

CREATE TABLE FORNECEDORES (
    CNPJ VARCHAR(50) NOT NULL,
    NOME_FANTASIA VARCHAR(50) NOT NULL,
    RAZAO_SOCIAL VARCHAR(50) NOT NULL,
    ENDEERECO_FORNECEDOR VARCHAR(50) NOT NULL,
    RAMO_ATIVIDADE VARCHAR(50) NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ)
);  

CREATE TABLE LOCALIZACOES(
    LOCALIZACAO_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SETOR INT NOT NULL,
    CORREDOR INT NOT NULL,
    PRATELEIRA INT NOT NULL,
    NIVEL INT NOT NULL
);

CREATE TABLE ITEM_ESTOQUE (
    ESTOQUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_ITEM INT NOT NULL,
    LOCALIZACAO_ID INT NOT NULL,
    QUANTIDADE_EM_ESTOQUE INT NOT NULL,
    CONSTRAINT ESTOQUE_ITEM_FK FOREIGN KEY (CODIGO_ITEM) REFERENCES ITENS(CODIGO_ITEM),
    CONSTRAINT ESTOQUE_LOCALIZACAO_FK FOREIGN KEY (LOCALIZACAO_ID) REFERENCES LOCALIZACOES(LOCALIZACAO_ID)
);

CREATE TABLE ENTRADAS_ESTOQUE (
    ENTRADA_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_ITEM INT NOT NULL,
    NUMERO_LOTE VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    FORNECEDOR_CNPJ VARCHAR(50) NOT NULL,
    FOREIGN KEY (CODIGO_ITEM) REFERENCES ITENS(CODIGO_ITEM),
    FOREIGN KEY (FORNECEDOR_CNPJ) REFERENCES FORNECEDORES(CNPJ)
);

CREATE TABLE SAIDAS_ESTOQUE (
    SAIDA_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_ITEM INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    ORIGEM_LOCALIZACAO INT,
    DESTINO VARCHAR(50) NOT NULL,
    FOREIGN KEY (CODIGO_ITEM) REFERENCES ITENS(CODIGO_ITEM),
    FOREIGN KEY (ORIGEM_LOCALIZACAO) REFERENCES LOCALIZACOES(LOCALIZACAO_ID)
);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (201, 'Tablet', 'Eletrônico', 'Tablet com tela de alta resolução', 0.5);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (202, 'Câmera de Segurança', 'Eletrônico', 'Câmera de segurança para monitoramento', 0.3);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (203, 'Mouse sem Fio', 'Periférico', 'Mouse óptico sem fio', 0.15);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (204, 'Impressora Laser', 'Periférico', 'Impressora a laser para documentos rápidos', 0.7);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (205, 'Monitor LED', 'Eletrônico', 'Monitor LED de 24 polegadas', 0.9);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (206, 'Roteador Wi-Fi', 'Rede', 'Roteador sem fio de alta velocidade', 0.2);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (207, 'Caixa de Som Bluetooth', 'Eletrônico', 'Caixa de som portátil ', 0.3);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (208, 'Teclado Bluetooth', 'Periférico', 'Teclado sem fio com conexão Bluetooth', 0.25);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (209, 'Carregador Portátil', 'Acessório', 'Carregador de bateria portátil', 0.1);

INSERT INTO ITENS (CODIGO_ITEM, NOME_ITEM, TIPO_ITEM, DESCRICAO_ITEM, VOLUME) VALUES (210, 'HD Externo', 'Armazenamento', 'HD externo de 1TB s', 0.6);


INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('1234567890002', 'ElectroTech', 'ElectroTech Eletrônicos Ltda.', 'Av. Eletrônica, 123, São Paulo, SP', 'Componentes Eletrônicos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('2223334440002', 'InovaTec', 'InovaTec S.A.', 'Rua Inovação, 456, Rio de Janeiro, RJ', 'Inovações Tecnológicas');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('3334445550002', 'TechSupply', 'TechSupply Comércio de Eletrônicos Ltda.', 'Praça da Tecnologia, 789, Belo Horizonte, MG', 'Distribuição de Eletrônicos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('4445556660002', 'MegaComponentes', 'MegaComponentes Ltda.', 'Alameda dos Componentes, 101, Porto Alegre, RS', 'Componentes Eletrônicos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('5556667770002', 'TechGlobal', 'TechGlobal Eletrônicos S.A.', 'Avenida da Inovação, 202, Curitiba, PR', 'Eletrônicos e Dispositivos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('6667778880002', 'ComponentesMaster', 'Componentes Master Ltda.', 'Rua dos Gadgets, 303, São Paulo, SP', 'Venda de Componentes Eletrônicos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('7778889990002', 'TechSuppliers', 'TechSuppliers Eletrônicos Ltda.', 'Avenida dos Eletrônicos, 404, Rio de Janeiro, RJ', 'Fornecimento de Eletrônicos');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('8889990000002', 'InovaTech', 'InovaTech Eletrônicos Ltda.', 'Rua da Inovação, 505, Belo Horizonte, MG', 'Soluções Eletrônicas');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('9990001110002', 'TechMasters', 'TechMasters Eletrônicos S.A.', 'Avenida Tech, 606, Porto Alegre, RS', 'Produtos Eletrônicos de Alta Qualidade');

INSERT INTO FORNECEDORES (CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, ENDEERECO_FORNECEDOR, RAMO_ATIVIDADE) VALUES ('0001112220002', 'GlobalEletronics', 'Global Eletronics Comércio Ltda.', 'Praça Global, 707, Curitiba, PR', 'Eletrônicos e Dispositivos de Última Geração');

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (1, 1, 1, 1);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (2, 2, 2, 2);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (3, 3, 3, 3);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (4, 4, 4, 4);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (5, 5, 5, 5);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (6, 6, 6, 6);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (7, 7, 7, 7);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (8, 8, 8, 8);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (9, 9, 9, 9);

INSERT INTO LOCALIZACOES (SETOR, CORREDOR, PRATELEIRA, NIVEL) VALUES (10, 10, 10, 10);

GRANT SELECT ON ITENS TO labdatabase;


GRANT SELECT, INSERT, UPDATE, DELETE ON FORNECEDORES TO labdatabase;
GRANT SELECT, INSERT, UPDATE, DELETE ON LOCALIZACOES TO labdatabase;
GRANT SELECT, INSERT, UPDATE, DELETE ON ITEM_ESTOQUE TO labdatabase;
GRANT SELECT, INSERT, UPDATE, DELETE ON ENTRADAS_ESTOQUE TO labdatabase;
GRANT SELECT, INSERT, UPDATE, DELETE ON SAIDAS_ESTOQUE TO labdatabase;